language:
- node_js
node_js:
- '6'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_REF: github.com/entrylabs/docs.git
    - GH_REPO: 'https://github.com/entrylabs/docs.git'
    - secure: >-
        nA4wNQyLGVCImbv9L6++RaLdkNwcltdpKkpSPukuFnBcy3g4r9aF2iKxKgLYZG5OGLwMq9kyfInGwR27q3BRETsC8dDbZA4UCYlm/KKyT3rZ5o0by6zTPdLHgRLDYpaju9WpODx1sTBPS1nVcxCwcIWhB0xZS/zotFldQrtgmfzYC0yp1P5biaHV1vU7j67MwJ5AXMsYxkeqo5clsUzeL4VvZM0yRQteirI9RsqBr5b+zx2wz1HXjrom++W63/wbVheMadYahIQeKwzJ9v3i1I8wVEAYmY/vF13HBfEgCCRJ6Ja0Xa4EqrUWHogFwJAkishIdk0l7VfLIa0xf2KktjRKDqAqsfdEWP+M1dVknClcDGUNL2prv/1tovGRA7rKEDLOP3B1PRRvQPfJBTzf8wEJ5+VMjLXVOMKF29sdHpaU/elk/UGFereQwUKtkfaeDmoi3mhPCtz0/RlGl3MGopH8mfN3x7JxryDLEYSYiaVirHL1zRiF1U5HvKPM4u38pDUbuZ7BMhTJBWqY3QjvhNK4w0Uof2q2/ujoRW1d1xb8e+8ft9QE/rF4ZeUyyKE2fdS3AQdc6NQ/78cQf3Hyamy9U/0OGKmxKLEHm9nrT1PQEwnurSj9rhLzsZ47AAi1qvSkKj1di4nBAAFryRyJHBEZUHQGBgdekMW6uqCfGtQ=
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.npm
branches:
  only:
    - master
install:
- yarn
script:
  - npm run deploy
